name: Release

on:
  create:

jobs:
  release:
    if: ${{ startsWith(github.ref, 'refs/tags/v') }}
    runs-on: ubuntu-latest

    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          version: v0.9.1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: "Fetch latest tag test"
        id: get-latest-tag
        uses: "WyriHaximus/github-action-get-previous-tag@v1"
      - name: Build and push Postgres 16 Timescale DB
        id: docker_build_16_timescaledb
        uses: docker/build-push-action@v3
        with:
          build-args: |
            PG_VERSION=16.3
            PG_MAJOR_VERSION=16
            VERSION=${{ steps.get-latest-tag.outputs.tag }}
          context: .
          file: ./pg16/Dockerfile-timescaledb
          push: true
          tags: |
            unixmask/postgres-timescale-pg_search:16
            unixmask/postgres-timescale-pg_search:16.3
      - name: Postgres 16 Image digest
        run: echo ${{ steps.docker_build_16.outputs.digest }}
      - name: Postgres 16 TimescaleDB Image digest
        run: echo ${{ steps.docker_build_16_timescaledb.outputs.digest }}
